### ISSUE TITLE
Airport codes

### ISSUE THREAD

**Issue by MarkG138** [lynnandtonic/airport-codes#615]
- [ ] ~~LBA-Leeds-Bradford Airport England~~ #503
- [x] BLK Backpool England
- [ ] ~~ISP Long Island-Islip,NY~~ #570 
- [ ] ~~SWF-Newburgh-Stewart, NY~~ #423 
- [x] SYR Syracuse, NY
- [ ] ~~ROC Rochester, NY~~ #505 
- [ ] ~~YTZ Toronto Island, Billy Bishop Airport~~ #271 
- [x] SEN Southend
- [ ] ~~BHD Belfast City, Northern Ireland~~ #382 
- [x] SNN Shannon, Ireland
- [ ] ~~ABZ Aberdeen, Scotland~~ #493 
- [x] DND Dundee Scotland
- [x] ~~INV Inverness Scotland~~ already on the site
- [x] PIK Prestwick Scotland
- [x] ~~NCL Newcastle, England~~ already on the site
- [x] MME Durham-Tees Valley, England
- [x] CBG Cambridge, England
- [x] NWI NOrwich, England
- [ ] ~~BRS Bristol England~~ #400 
- [x] ~~CWL Cardiff, Wales~~ already on the site
- [x] NQY Newquay England
- [x] SOU Southampton England
- [x] ~~BOH Bournemouth, England~~ already on the site
- [x] LGG Liege, Belgium
- [x] ~~RTM Rotterdam, Netherlands~~ #462 
- [x] ~~EIN Eindhoven, Netherlands~~ already on the site
- [x] HHN Frankfurt-Hahn Germany
- [x] MST Maastricht, Netherlands

**Comment by ncrohn** [comment]
Updated ticket to mark airports we have issues open for and link them.

**Comment by lynnandtonic** [comment]
Handled all airports in this list that don't have other issues. So closing.
